package io.meorg.code.view.constants

object RepositoryConstants {
    const val affiliateMerchantIndices = "affiliate_merchant"
    const val merchantIndices = "merchant"
    const val offerIndices = "offer"
    const val productIndices = "product"
    const val searchProductIndices = "search_product"
    const val assocProductIndices = "assoc_product"
    const val priceComparisonIndices = "price_comparison"
    const val credentialsIndices = "credential"
    const val credentialsCollection = "credentials"
    const val productCategoryIndices = "product_category"
    const val faqIndices = "faq"
    const val topicIndices = "topic"
    const val suggestIndices = "suggest"
    const val cityCollection = "city"
    const val countryCollection = "country"
    const val mailTemplateCollection = "mail_template"
    const val bannerCollection = "banner"
    const val priceHistoryCollection = "price_history"
    const val adminLogCollection = "admin_log"
    const val feedLogCollection = "feed_log"
    const val notFoundPurchaseCollection = "not_found_purchase"
    const val sliderConfigCollection = "slider_config"
    const val adminUserCollection = "admin_user"
    const val appConfigCollection = "app_config"
    const val compilationConfigCollection = "compilation_config"
    const val helpCollection = "help"
}